from __future__ import annotations

PRODUCT_NAME = "Reason Assembly"
PRODUCT_SLUG = "reason-assembly"
PRODUCT_DESCRIPTOR = "An evidence-backed agent council built for empirical evaluation."
VERSION = "0.6.0"
RELEASE_TAG = f"v{VERSION}"

CANONICAL_CLI = PRODUCT_SLUG
CANONICAL_SKILL = PRODUCT_SLUG

STATE_ENV = "REASON_ASSEMBLY_STATE"
PROXY_CONFIG_ENV = "REASON_ASSEMBLY_PROXY_CONFIG"
PROXY_ADAPTER_CONFIG_ENV = "CCYPROXY_CONFIG"
EPHEMERAL_KEY_ENV = "REASON_ASSEMBLY_EPHEMERAL_KEY"
ROUTING_POLICY_ENV = "REASON_ASSEMBLY_ROUTING_POLICY"
WORKER_EXECUTABLE_ENV = "REASON_ASSEMBLY_WORKER"

USER_AGENT = f"{PRODUCT_SLUG}/{VERSION}"
VERIFICATION_USER_AGENT = f"{PRODUCT_SLUG}-v4/{VERSION}"
SESSION_NAMESPACE = f"{PRODUCT_SLUG}:v4"
METADATA_CLIENT_VERSION = f"{PRODUCT_SLUG}-v4"
BRANCH_NAMESPACE = PRODUCT_SLUG
LOCAL_COMMIT_NAME = PRODUCT_NAME
LOCAL_COMMIT_EMAIL = "reason-assembly@local"
LOCAL_COMMIT_PREFIX = f"{PRODUCT_SLUG}:"
